# Generated by Django 5.1.2 on 2024-10-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtmodel',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('DELETED', 'Deleted')], default='UNPAID', max_length=255),
        ),
    ]
