# Generated by Django 5.1.2 on 2024-11-01 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_alter_debtmodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencymodel',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='debtmodel',
            options={'verbose_name': 'Debt', 'verbose_name_plural': 'Debts'},
        ),
    ]
