# Generated by Django 5.1.2 on 2024-11-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_alter_currencymodel_options_alter_debtmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtmodel',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
