# Generated by Django 5.1.2 on 2024-11-01 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_debtmodel_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtmodel',
            name='paid_amount',
        ),
    ]
