# Generated by Django 5.1.2 on 2024-11-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0005_remove_debtmodel_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtmodel',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
