# Generated by Django 5.1.2 on 2024-11-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0006_debtmodel_remaining_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtmodel',
            name='last_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
